### ISSUE TITLE
Regular expression to match all emoji

### ISSUE THREAD

**Issue by tonton-pixel** [tc39/proposal-regexp-unicode-sequence-properties#13]
I've just released a Node module called [emoji-patterns](https://github.com/tonton-pixel/emoji-patterns) which provides basic and compound patterns to match all emoji or just fully-qualified (keyboard) emoji.

I've been using this module in my own [Electron project](https://github.com/tonton-pixel/unicode-plus) since a while ago, and I tested it successfully on the set of 3570 emoji found in `emoji-test.txt`.

IMHO, the components of `reEmoji` should be differently organized, more specifically they should go from the longest to the shortest, since a regular expression engine is *eager* and stops searching as soon as it finds a valid match, i.e., it always returns the leftmost match.

Also, I think that `\p{Emoji_Modifier}` should not be optional; actually, `\p{Emoji_Modifier_Base}\p{Emoji_Modifier}` can be safely replaced by `\p{Emoji_Modifier_Sequence}`.

And finally, ` \p{Emoji_Keycap_Sequence}` should be included as well...

So:

```javascript
const reEmoji = /\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|\p{Emoji_Presentation}|\p{Emoji}\uFE0F|\p{Emoji_Flag_Sequence}|\p{Emoji_Tag_Sequence}|\p{Emoji_ZWJ_Sequence}/gu;
```
should be instead:

```javascript
const reEmoji = /\p{Emoji_ZWJ_Sequence}|\p{Emoji_Keycap_Sequence}|\p{Emoji_Flag_Sequence}|\p{Emoji_Tag_Sequence}|\p{Emoji_Modifier_Base}\p{Emoji_Modifier}|\p{Emoji_Presentation}|\p{Emoji}\uFE0F/gu;
```

or possibly:

```javascript
const reEmoji = /\p{Emoji_ZWJ_Sequence}|\p{Emoji_Keycap_Sequence}|\p{Emoji_Flag_Sequence}|\p{Emoji_Tag_Sequence}|\p{Emoji_Modifier_Sequence}|\p{Emoji_Presentation}|\p{Emoji}\uFE0F/gu;
```

HTH,

-- Michel Mariani

**Comment by mathiasbynens** [comment]
Thanks for your comments here and on [the emoji-regex project](https://github.com/mathiasbynens/emoji-regex/issues/43#issuecomment-417718328)!

https://github.com/tc39/proposal-regexp-unicode-sequence-properties#matching-emoji-sequences has been updated.
